// Build script for dsh-theme-palettes.
//
// Generates the three install artifacts from the ESM sources
// (src/client.js, src/palettes.js, src/settings.js) and this package's
// manifest:
//
//   client.js          the `./client` export: a classic script that registers
//                      the module factory with the shell's
//                      `window.__ModuleLoader__.load` — the exact shape the
//                      dsh client-modules host half serves to the browser
//                      (raw ESM would be a SyntaxError there). The factory
//                      inlines the runtime core (`apply`), the palette catalog,
//                      and the settings UI (`registerPaletteSettings`).
//   index.js           the host-half no-op: the composition row's host entry
//                      imports it, which keeps the row's fiber active so the
//                      client-modules scan qualifies the package.
//   cordis.patch.yml   the dsh.bundle patch layer: inserts this package's own
//                      row. `dsh plugin --profile <name> add` reconciles any
//                      dependency declaring `dsh.bundle` into the profile's
//                      layer stack, so this patch makes the install
//                      self-activating on the next restart.
//
// Zero dependencies: plain `node build.mjs`. Deliberately NOT a `prepare`
// hook: pnpm 10+ refuses to run lifecycle scripts of git-hosted packages
// unless they are allowlisted, and this package needs no build at install
// time — the generated artifacts are committed. `prepublishOnly` rebuilds
// them right before an npm/pnpm publish.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  inject,
  apply,
  SERVICE_NAME,
  SETTINGS_NAMESPACE,
  LAYER_SOURCE,
  DEFAULT_MAPPING,
} from './src/client.js'
import { PALETTES } from './src/palettes.js'
import { registerPaletteSettings } from './src/settings.js'

const root = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// The factory must register under the package name: the boot graph is keyed
// by it, and the graph row id is what the shell imports.
const CLIENT_ID = pkg.name

writeFileSync(join(root, 'client.js'), `// Generated by build.mjs from src/*.js — do not edit by hand.
// dsh client bundle: registers the module factory for ${CLIENT_ID}.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(CLIENT_ID)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    const React = require("react");
    const inject = ${JSON.stringify(inject)};
    const SERVICE_NAME = ${JSON.stringify(SERVICE_NAME)};
    const SETTINGS_NAMESPACE = ${JSON.stringify(SETTINGS_NAMESPACE)};
    const LAYER_SOURCE = ${JSON.stringify(LAYER_SOURCE)};
    const DEFAULT_MAPPING = ${JSON.stringify(DEFAULT_MAPPING)};
    const PALETTES = ${JSON.stringify(PALETTES)};

    ${apply}

    ${registerPaletteSettings}

    exports.inject = inject;
    exports.apply = apply;
    return module.exports;
  }
});
`)

writeFileSync(join(root, 'index.js'), `// Generated by build.mjs — do not edit by hand.
// Host half, intentionally empty: the composition row's host entry imports
// this module so the row mounts active (the client-modules scan skips rows
// without an active host fiber). The theme service is browser-only, so there
// is nothing to do on the host.
export function apply() {}
`)

writeFileSync(join(root, 'cordis.patch.yml'), `# Generated by build.mjs — do not edit by hand.
# ${CLIENT_ID} bundle patch: applied when this package joins a profile's
# dsh.profile.bundles layer stack (dsh plugin --profile <name> add reconciles a
# dsh.bundle-declaring dependency there automatically). Inserts the palette
# row, which the client-modules host half scans into window.__DSH_BOOT__ and
# serves at /plugins/${CLIENT_ID}/client.js.
- insert:
    - id: theme-palettes
      name: ${CLIENT_ID}
`)

console.log(`built ${pkg.name}: client.js, index.js, cordis.patch.yml`)
