// Build script for dsh-theme-vscode-red.
//
// Generates the three install artifacts from the single ESM source
// (src/client.js) and this package's manifest:
//
//   client.js          the `./client` export: a classic script that registers
//                      the module factory with the shell's
//                      `window.__ModuleLoader__.load` — the exact shape the
//                      dsh client-modules host half serves to the browser
//                      (raw ESM would be a SyntaxError there).
//   index.js           the host-half no-op: the composition row's host entry
//                      imports it, which keeps the row's fiber active so the
//                      client-modules scan qualifies the package.
//   cordis.patch.yml   the dsh.bundle patch layer: inserts this package's own
//                      row. `dsh plugin --profile <name> add` reconciles any
//                      dependency declaring `dsh.bundle` into the profile's
//                      layer stack, so this patch makes the install
//                      self-activating on the next restart.
//
// Zero dependencies: plain `node build.mjs`. Deliberately NOT a `prepare`
// hook: pnpm 10+ refuses to run lifecycle scripts of git-hosted packages
// unless they are allowlisted, and this package needs no build at install
// time — the generated artifacts are committed. `prepublishOnly` rebuilds
// them right before an npm/pnpm publish.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { THEME_ID, TOKENS, OVERRIDE_SOURCE, inject, apply } from './src/client.js'

const root = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// The factory must register under the package name: the boot graph is keyed
// by it, and the graph row id is what the shell imports.
const CLIENT_ID = pkg.name

writeFileSync(join(root, 'client.js'), `// Generated by build.mjs from src/client.js — do not edit by hand.
// dsh client bundle: registers the module factory for ${CLIENT_ID}.
window.__ModuleLoader__.load({
  id: ${JSON.stringify(CLIENT_ID)},
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    const inject = ${JSON.stringify(inject)};
    const THEME_ID = ${JSON.stringify(THEME_ID)}
    const OVERRIDE_SOURCE = ${JSON.stringify(OVERRIDE_SOURCE)}
    const TOKENS = ${JSON.stringify(TOKENS, null, 2)}

    ${apply}

    exports.inject = inject;
    exports.apply = apply;
    exports.THEME_ID = THEME_ID;
    exports.OVERRIDE_SOURCE = OVERRIDE_SOURCE;
    exports.TOKENS = TOKENS;
    return module.exports;
  }
});
`)

writeFileSync(join(root, 'index.js'), `// Generated by build.mjs — do not edit by hand.
// Host half, intentionally empty: the composition row's host entry imports
// this module so the row mounts active (the client-modules scan skips rows
// without an active host fiber). The theme service is browser-only, so there
// is nothing to do on the host.
export function apply() {}
`)

writeFileSync(join(root, 'cordis.patch.yml'), `# Generated by build.mjs — do not edit by hand.
# dsh-theme-vscode-red bundle patch: applied when this package joins a
# profile's dsh.profile.bundles layer stack (dsh plugin --profile <name> add
# reconciles a dsh.bundle-declaring dependency there automatically). Inserts
# the theme's own row, which the client-modules host half scans into
# window.__DSH_BOOT__ and serves at /plugins/${CLIENT_ID}/client.js.
- insert:
    - id: theme-vscode-red
      name: ${CLIENT_ID}
`)

console.log(`built ${pkg.name}: client.js, index.js, cordis.patch.yml`)
