// Generated by build.mjs from src/host.js and src/host-schema.js — do not edit by hand.
// Host half: registers the durable settings namespace on the Host settings
// seam. rc7 serves every registered namespace on the settings wire, so this
// registration is the whole persistence surface — no private HTTP route.
import z from '@deepseek-ai/schemastery'

// dsh-theme-palettes — Host namespace contract (pure, dependency-free).
//
// rc7: the harness settings WIRE serves every namespace a Host plugin
// registers (the old hardcoded allowlist and the `settings-not-exposed` error
// are gone), so the Host half only has to register the namespace on the Host
// settings seam. The wire then exposes it to the browser through the standard
// settings scope, which the browser half reads and writes — and the Plugin
// configuration tab dispatches a card for it because the card is keyed by
// this same namespace.
//
// This module carries the contract pieces the zero-dependency test suite
// exercises; `src/host.js` wires them to the real schemastery import.

/** Settings namespace owned by this package (lowercase kebab-case). */
export const SETTINGS_NAMESPACE = 'theme-palettes'

/** Fallback mapping used until a user override exists. */
export const HOST_DEFAULT_MAPPING = { dark: 'default', light: 'default' }

/**
 * Build the namespace schema. Receives a schemastery-shaped `z` so the
 * contract test can pass a minimal fake and stay dependency-free.
 */
export function buildSchema(z) {
  return z.object({
    dark: z.string().default(HOST_DEFAULT_MAPPING.dark),
    light: z.string().default(HOST_DEFAULT_MAPPING.light),
  })
}

/** The exact registration call the Host half makes on the settings seam. */
export function registerNamespace(settings, z) {
  settings.register(SETTINGS_NAMESPACE, buildSchema(z))
}

// dsh-theme-palettes — Host half.
//
// One job, behind an optional-service injection so the row still mounts on
// compositions that lack the settings seam:
//
//   Register the durable `theme-palettes` settings namespace on the Host
//   settings seam. rc7 serves every registered namespace on the settings
//   WIRE (the old hardcoded allowlist is gone), so this single registration
//   is what makes the mapping reach the browser through the standard
//   settings scope — and what makes the Plugin configuration tab dispatch
//   the "Theme palettes" card, which is keyed by this same namespace.
//
// `build.mjs` inlines this module into the generated `index.js`; the
// contract pieces live in `src/host-schema.js` so the zero-dependency test
// suite can exercise them.



export function apply(ctx) {
  // Registration rides the settings seam's own lifecycle: if the provider
  // unmounts or this row is disposed, the namespace goes with it.
  ctx.inject(['settings'], (settingsCtx) => {
    registerNamespace(settingsCtx.settings, z)
  })
}
