// Generated by build.mjs — do not edit by hand.
// Host half, intentionally empty: the composition row's host entry imports
// this module so the row mounts active (the client-modules scan skips rows
// without an active host fiber). The theme service is browser-only, so there
// is nothing to do on the host.
export function apply() {}
