// Generated by build.mjs from src/host.js and src/host-schema.js — do not edit by hand.
// Host half: registers the durable settings namespace on the Host settings
// seam and serves the private HTTP route the browser half persists through —
// the settings WIRE serves only a hardcoded namespace allowlist, so a
// third-party web package cannot use the standard settings RPC.
import z from '@deepseek-ai/schemastery'

// dsh-theme-palettes — Host namespace contract (pure, dependency-free).
//
// The harness's settings WIRE serves only a hardcoded namespace allowlist, so
// a third-party web package cannot read or write its own settings namespace
// through the standard settings RPC. The Host half therefore owns the
// namespace on the Host settings seam directly (`settings.register`), which
// persists it into the same user settings document as first-party namespaces
// (settings.yaml), and exposes a small private HTTP surface the browser half
// uses instead of the gated wire.
//
// This module carries the contract pieces the zero-dependency test suite
// exercises; `src/host.js` wires them to the real schemastery import.

/** Settings namespace owned by this package (lowercase kebab-case). */
export const SETTINGS_NAMESPACE = 'theme-palettes'

/** Fallback mapping used until a user override exists. */
export const HOST_DEFAULT_MAPPING = { dark: 'default', light: 'default' }

/** Private HTTP route the browser half reads and writes through. */
export const HTTP_ROUTE = '/api/theme-palettes'

/**
 * Build the namespace schema. Receives a schemastery-shaped `z` so the
 * contract test can pass a minimal fake and stay dependency-free.
 */
export function buildSchema(z) {
  return z.object({
    dark: z.string().default(HOST_DEFAULT_MAPPING.dark),
    light: z.string().default(HOST_DEFAULT_MAPPING.light),
  })
}

/** The exact registration call the Host half makes on the settings seam. */
export function registerNamespace(settings, z) {
  settings.register(SETTINGS_NAMESPACE, buildSchema(z))
}

/** One mutate op the browser half may send (subset of the settings seam). */
export function normalizeOps(input) {
  if (!Array.isArray(input) || input.length === 0) {
    throw new TypeError('ops must be a non-empty array of { op: "set" | "unset", path: string[] }')
  }
  for (const op of input) {
    if (typeof op !== 'object' || op === null) throw new TypeError('each op must be an object')
    if (op.op !== 'set' && op.op !== 'unset') throw new TypeError('op must be "set" or "unset"')
    if (!Array.isArray(op.path) || op.path.length === 0 || op.path.some((part) => typeof part !== 'string')) {
      throw new TypeError('op.path must be a non-empty array of strings')
    }
    if (op.op === 'set' && !['dark', 'light'].includes(op.path[0])) {
      throw new TypeError(`unknown field ${JSON.stringify(op.path[0])} (expected "dark" or "light")`)
    }
    if (op.op === 'set' && typeof op.value !== 'string') {
      throw new TypeError('op.value must be a string palette id')
    }
    if (op.op === 'unset' && !['dark', 'light'].includes(op.path[0])) {
      throw new TypeError(`unknown field ${JSON.stringify(op.path[0])} (expected "dark" or "light")`)
    }
  }
  return input.map((op) => ({ op: op.op, path: [...op.path], ...(op.op === 'set' ? { value: op.value } : {}) }))
}

// dsh-theme-palettes — Host half.
//
// Two jobs, both behind optional-service injections so the row still mounts
// on compositions that lack them:
//
//   1. Register the durable `theme-palettes` settings namespace on the Host
//      settings seam. Without this, writes fail even when the wire would
//      serve the namespace.
//   2. Serve the private HTTP route the browser half uses. The standard
//      settings wire refuses third-party namespaces (`settings-not-exposed`,
//      a hardcoded allowlist in the harness api-proxy), so the browser half
//      talks to this route instead; persistence still lands in the same user
//      settings document (settings.yaml) via the mounted settings provider.
//
// `build.mjs` inlines this module into the generated `index.js`; the
// contract pieces live in `src/host-schema.js` so the zero-dependency test
// suite can exercise them.



const MAX_BODY_BYTES = 64 * 1024

function jsonResponse(res, status, body) {
  const text = JSON.stringify(body)
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-store',
  })
  res.end(text)
}

function readJsonBody(req) {
  return new Promise((resolve, reject) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > MAX_BODY_BYTES) {
        reject(new Error('request body too large'))
        req.destroy()
      }
    })
    req.on('end', () => {
      try {
        resolve(data.length === 0 ? {} : JSON.parse(data))
      } catch (error) {
        reject(new Error('request body is not valid JSON'))
      }
    })
    req.on('error', reject)
  })
}

/**
 * Project the registered namespace onto the wire shape the browser half
 * consumes: resolved value, revision, and writability.
 */
function describeNamespace(settings) {
  const descriptor = settings.describe().find((candidate) => String(candidate.ns) === SETTINGS_NAMESPACE)
  if (descriptor === undefined) return undefined
  return {
    value: descriptor.value,
    revision: descriptor.revision,
    writable: settings.writable,
  }
}

export function apply(ctx) {
  // Registration rides the settings seam's own lifecycle: if the provider
  // unmounts or this row is disposed, the namespace goes with it.
  ctx.inject(['settings'], (settingsCtx) => {
    registerNamespace(settingsCtx.settings, z)
  })

  ctx.inject(['webServer'], (httpCtx) => {
    const settings = () => httpCtx.get('settings')
    httpCtx.effect(() => httpCtx.webServer.register({
      kind: 'exact',
      path: HTTP_ROUTE,
      async handler(req, res) {
        const seam = settings()
        if (seam === undefined) {
          jsonResponse(res, 503, { ok: false, error: 'settings provider not mounted' })
          return
        }
        try {
          if (req.method === 'GET') {
            const view = describeNamespace(seam)
            if (view === undefined) {
              jsonResponse(res, 404, { ok: false, error: `settings namespace "${SETTINGS_NAMESPACE}" is not registered` })
              return
            }
            jsonResponse(res, 200, { ok: true, ...view })
            return
          }
          if (req.method === 'POST') {
            const body = await readJsonBody(req)
            const ops = normalizeOps(body.ops)
            const expectedRevision = typeof body.expectedRevision === 'number' ? body.expectedRevision : undefined
            await seam.mutate(SETTINGS_NAMESPACE, ops, expectedRevision)
            const view = describeNamespace(seam)
            jsonResponse(res, 200, { ok: true, ...view })
            return
          }
          jsonResponse(res, 405, { ok: false, error: `method ${req.method ?? 'unknown'} not allowed (GET, POST)` })
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error)
          const code = error && error.code === 'SETTINGS_CONFLICT' ? 'settings-conflict' : 'settings-rejected'
          jsonResponse(res, 400, { ok: false, error: message, code })
        }
      },
    }), `theme-palettes: ${HTTP_ROUTE}`)
  })
}
